// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIibhtjeQZuV5BSvZv05vNG6zSjyTWqZw',
    appId: '1:326346807376:web:e42179ba76747399f51955',
    messagingSenderId: '326346807376',
    projectId: 'push-notification-5e7df',
    authDomain: 'push-notification-5e7df.firebaseapp.com',
    storageBucket: 'push-notification-5e7df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANjbJXXfWOvC2qpDygJFUg7mrfSzf6eL8',
    appId: '1:326346807376:android:775e17fc11b41b66f51955',
    messagingSenderId: '326346807376',
    projectId: 'push-notification-5e7df',
    storageBucket: 'push-notification-5e7df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlTNzdKop3QxyHbp3vfhqq-XzEQh8jBuI',
    appId: '1:326346807376:ios:8abcfa8aec57f6b3f51955',
    messagingSenderId: '326346807376',
    projectId: 'push-notification-5e7df',
    storageBucket: 'push-notification-5e7df.appspot.com',
    iosBundleId: 'com.kaaikani.kaaikani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlTNzdKop3QxyHbp3vfhqq-XzEQh8jBuI',
    appId: '1:326346807376:ios:8abcfa8aec57f6b3f51955',
    messagingSenderId: '326346807376',
    projectId: 'push-notification-5e7df',
    storageBucket: 'push-notification-5e7df.appspot.com',
    iosBundleId: 'com.kaaikani.kaaikani',
  );
}
