// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Wc9zKgjxrK4v13i3DScrrGGEEz8mGVg',
    appId: '1:925683676829:web:90cf3b8d75af67af32c674',
    messagingSenderId: '925683676829',
    projectId: 'push-notification-5d56d',
    authDomain: 'push-notification-5d56d.firebaseapp.com',
    storageBucket: 'push-notification-5d56d.appspot.com',
    measurementId: 'G-649D583TH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6D98NJ0zhzq9MzitW2LifnKcFkrxvqcI',
    appId: '1:925683676829:android:36bd81054b003a3932c674',
    messagingSenderId: '925683676829',
    projectId: 'push-notification-5d56d',
    storageBucket: 'push-notification-5d56d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoyw-KU61RO33DGU29ejZBdQhHPtN5uDA',
    appId: '1:925683676829:ios:732d39181aa1510332c674',
    messagingSenderId: '925683676829',
    projectId: 'push-notification-5d56d',
    storageBucket: 'push-notification-5d56d.appspot.com',
    iosBundleId: 'com.kaaikani.kaaikani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoyw-KU61RO33DGU29ejZBdQhHPtN5uDA',
    appId: '1:925683676829:ios:732d39181aa1510332c674',
    messagingSenderId: '925683676829',
    projectId: 'push-notification-5d56d',
    storageBucket: 'push-notification-5d56d.appspot.com',
    iosBundleId: 'com.kaaikani.kaaikani',
  );
}
